version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pepsico_db
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      DEBUG: "1"
      DJANGO_ENV: development
      # SECRET_KEY: your_secret_key
      # DATABASE_URL: postgres://postgres:password@db:5432/pepsico_db
    depends_on:
      - db
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DEBUG: "1"
      DJANGO_ENV: development
      # SECRET_KEY: your_secret_key
      # DATABASE_URL: postgres://postgres:password@db:5432/pepsico_db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - backend

  redis:
    image: redis:6
    networks:
      - backend

volumes:
  postgres_data:


networks:
  backend:
    driver: bridge
