version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: library_db
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      DJANGO_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/library_db
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:


networks:
  backend:
    driver: bridge
