# Generated by Django 5.1.1 on 2024-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
